name: My First CI Pipeline

on:
  push:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: - uses: actions/checkout@v4

      - name: Run Python file
        run: python app.py
